package br.com.infox.telas;
//importando bibliotecas

import java.sql.*;
//importa modulo de conexão
import br.com.infox.dal.ModuloConexao;
import java.awt.Color;
import javax.swing.JOptionPane;

// aqui começa a conexão com o banco de dados
public class TelaLogin extends javax.swing.JFrame {
    //aqui eu vou usar a variavel conexao 

    Connection conexao = null;
//duas variaveis especiais de apoio a conexao ao BD
//PreparedStatement é outro framework, pst é o nome
    PreparedStatement pst = null; //está variavel prepara a consulta ao BD
    ResultSet rs = null; //ela vai executar a variavel de cima 

//criando o metodo logar
    public void logar() {
        //consulta ao banco de dados
        String sql = "select * from tbusuarios where login=? and senha =?";
        // dando o try
        try {
            //as linhas abaixo preparam a consulta ao banco em função do que 
            //foi digitado na janela de login
            // o ? é substituido pelo conteudo das variaveis

            pst = conexao.prepareStatement(sql);
            // o que for digitado em txtusuario armazene em pst (campo 1)
            pst.setString(1, txtusuario.getText());
            // o que for digitado em txtsenha armazene em pst (campo 2)
            pst.setString(2, txtsenha.getText());

            // a linha abaixo executa a query (consulta ao BD)
            rs = pst.executeQuery();

            // se existir usuario e senha correspondente 
            if (rs.next()) { //next() é a forma de verificar no BD 

                // a linha abaixo obtem o conteudo do campo perfil do BD
                String perfil = rs.getString(6);
                //System.out.println(perfil);

                //a estrutura abaixo faz o tratamento do perfil do usuário
                if (perfil.equals("admin")) { //por não conseguir poder usar == entre
                    //Strings, usa-se equals (perfil == 'admin')

                    // criando um objeto "principal" da classe "TelaPrincipal"
                    TelaPrincipal principal = new TelaPrincipal();
                    //essa linha abrirá a tela principal
                    principal.setVisible(true);

                    //mostra para ADMs os menus ocultos 
                    TelaPrincipal.MRServiços.setEnabled(true);
                    TelaPrincipal.MCUsuarios.setEnabled(true);
                    
                    //Fazendo o nome do usuario no BD aparecer no lblUsuario
                    TelaPrincipal.LBLUsuario.setText(rs.getString(2));
                    
                    //muda a cor do lblusuario
                    TelaPrincipal.LBLUsuario.setForeground(Color.green);
                    

                    this.dispose(); //esse codigo fecha a janela TelaLogin

                } else {

                    // criando um objeto "principal" da classe "TelaPrincipal"
                    TelaPrincipal principal = new TelaPrincipal();
                    //essa linha abrirá a tela principal
                    principal.setVisible(true);
                    //Fazendo o nome do usuario no BD aparecer no lblUsuario
                    TelaPrincipal.LBLUsuario.setText(rs.getString(2));
                    
                    this.dispose(); //esse codigo fecha a janela TelaLogin
                    
                }
            } else { // se não existir mostrará a mensagem abaixo 
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválido(s)");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println("ERRO NO CÓDIGO: " + e);
        }

    }

    public TelaLogin() {
        //temos aqui a inicialização de todos os componentes
        initComponents();
        //aqui eu devo chamar o metodo conector, que eu criei em ModuloConexao
        conexao = ModuloConexao.conector();
        //A linha abaixo mostra a conexão caso dê certo
        //System.out.println(conexao);

        if (conexao != null) {

            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/bdconectado.png")));
        } else {

            lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/bdnconectado.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        Blogin = new javax.swing.JButton();
        txtsenha = new javax.swing.JPasswordField();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("X System - Login");
        setResizable(false);

        lblUsuario.setText("Usuário :");

        lblSenha.setText("Senha :");

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusuarioKeyPressed(evt);
            }
        });

        Blogin.setText("Login");
        Blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloginActionPerformed(evt);
            }
        });
        Blogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BloginKeyPressed(evt);
            }
        });

        txtsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsenhaKeyPressed(evt);
            }
        });

        lblStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/bdconectado.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Blogin)
                        .addGap(186, 186, 186))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addComponent(lblSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtusuario)
                            .addComponent(txtsenha, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuario)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Blogin)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setSize(new java.awt.Dimension(442, 202));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloginActionPerformed
        // Chamando o metodo logar ao apertar o botão de login (Blogin)
        logar();
    }//GEN-LAST:event_BloginActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyPressed
        //caso digite enter
        if(evt.getKeyCode() == evt.VK_ENTER){
            //ele irá para a barra de texto txtsenha
            txtsenha.requestFocus();
        }
        
        
    }//GEN-LAST:event_txtusuarioKeyPressed

    private void txtsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsenhaKeyPressed
        //caso digite enter
        if(evt.getKeyCode() == evt.VK_ENTER){
            //ele vai logar direto
            logar();
        }
    }//GEN-LAST:event_txtsenhaKeyPressed

    private void BloginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BloginKeyPressed
        //caso precione enter
        if (evt.getKeyCode() == evt.VK_ENTER){
            
            //chama a tela logar 
            logar();
        }
        
        
        
        
        
    }//GEN-LAST:event_BloginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
